engines:
  eslint:
    enabled: true
    checks:
      fatal:
        enabled: false
  duplication:
    enabled: true
    languages:
    - javascript
    checks:
      Similar code:
        enabled: false
  fixme:
    enabled: true
    checks:
      XXX:
        enabled: false
